### ISSUE TITLE
Não dividir as pastas por semestres

### ISSUE THREAD

**Issue by brunomacabeusbr** [CAECOMP/provas#11]
Creio que seja melhor não dividir as pastas por semestre, pois fica confuso por ter cadeiras que mudaram de semestres (como sistemas lineares). Sempre fico confuso se está em relação a grade nova ou antiga.
Aliás, tem gente bagunçada como eu que nem sabe de qual semestre é a cadeira que está cursando.

Que tal apenas colocar todas as pastas na raiz?

**Comment by zneto** [comment]
Concordo plenamente

**Comment by jefponte** [comment]
Concordo plenamente

**Comment by jefponte** [comment]
Ninguém disse mais nada, então acho que temos um consenso.

**Comment by jefponte** [comment]
Feito.
